namespace Volt
{
public enum WWiseEvents : uint
{
Play_Enemy_Footsteps	 = 0,
Play_Switch	 = 1,
Play_Nuke	 = 2,
Play_MainMenu_Music	 = 3,
Play_Phone	 = 4,
Play_Barricade_Break	 = 5,
Play_MaxAmmo	 = 6,
Play_NewRound	 = 7,
Play_DoublePoints	 = 8,
Play_Death	 = 9,
Play_Shotgun_Reload	 = 10,
Play_Phone_Far	 = 11,
Play_TakeDamage	 = 12,
Play_UI_Hover	 = 13,
Play_Shotgun_Pumpback	 = 14,
Play_Footstep	 = 15,
Play_UI_Click	 = 16,
Play_SpendMoney	 = 17,
Play_Pistol_Reload	 = 18,
Play_Enemy_TakeDamage	 = 19,
Play_Enemy_Attack	 = 20,
Play_Automatic_Shoot	 = 21,
Play_ChangeWeapon_To	 = 22,
Play_Shotgun_Shot	 = 23,
Play_Music	 = 24,
Play_Pistol_Shoot	 = 25,
Play_Melee	 = 26,
Play_Enemy_Death	 = 27,
Play_Enemy_Growl	 = 28,
Play_UpgradeWeapon	 = 29,
Stop_Barricade_Repair	 = 30,
Play_Barricade_Repair	 = 31,
Play_BoltAction_Shoot	 = 32,
Play_InstaKill	 = 33,
Play_BoltAction_Bolt	 = 34,
Play_Jump	 = 35,
Play_Music_3D	 = 36,
Play_Carpenter	 = 37,
Play_Automatic_Reload	 = 38,
Play_ChangeWeapon_From	 = 39,
Play_BoltAction_Reload	 = 40,
Play_Land	 = 41,
}
}
