#include "vtpch.h"
#include "Volt/Asset/AssetTypes.h"

VT_REGISTER_ASSET_TYPE(AnimatedCharacter);
VT_REGISTER_ASSET_TYPE(Animation);
VT_REGISTER_ASSET_TYPE(MotionWeave);
VT_REGISTER_ASSET_TYPE(Mesh);
VT_REGISTER_ASSET_TYPE(Scene);
VT_REGISTER_ASSET_TYPE(Skeleton);
VT_REGISTER_ASSET_TYPE(ParticlePreset);
VT_REGISTER_ASSET_TYPE(Material);
VT_REGISTER_ASSET_TYPE(PostProcessingStack);
VT_REGISTER_ASSET_TYPE(Prefab);
VT_REGISTER_ASSET_TYPE(Texture);
VT_REGISTER_ASSET_TYPE(PostProcessingMaterial);
VT_REGISTER_ASSET_TYPE(Timeline);
VT_REGISTER_ASSET_TYPE(NavMesh);
VT_REGISTER_ASSET_TYPE(PhysicsMaterial);
VT_REGISTER_ASSET_TYPE(NetContract);
VT_REGISTER_ASSET_TYPE(TextureSource);
VT_REGISTER_ASSET_TYPE(ShaderDefinition);
VT_REGISTER_ASSET_TYPE(ShaderSource);
VT_REGISTER_ASSET_TYPE(MeshSource);
VT_REGISTER_ASSET_TYPE(BlendSpace);
VT_REGISTER_ASSET_TYPE(BehaviorGraph);
VT_REGISTER_ASSET_TYPE(MonoScript);
