IncludeDir = {}
IncludeDir["GLFW"] = "%{wks.location}/Volt/vendor/GLFW/include"
IncludeDir["ImGui"] = "%{wks.location}/Volt/vendor/ImGui"
IncludeDir["spdlog"] = "%{wks.location}/Volt/vendor/spdlog/include"
IncludeDir["yaml"] = "%{wks.location}/Volt/vendor/yaml-cpp/include"
IncludeDir["Optick"] = "%{wks.location}/Volt/vendor/Optick/src"
IncludeDir["tracy"] = "%{wks.location}/Volt/vendor/tracy/public/tracy"
IncludeDir["tinyddsloader"] = "%{wks.location}/Volt/vendor/tinyddsloader/"
IncludeDir["imgui_notify"] = "%{wks.location}/Volt/vendor/imgui-notify/"
IncludeDir["ImGuizmo"] = "%{wks.location}/Volt/vendor/ImGuizmo/"
IncludeDir["glm"] = "%{wks.location}/Volt/vendor/glm"
IncludeDir["DirectXTK"] = "%{wks.location}/Volt/vendor/DirectXTK"
IncludeDir["imgui_node_editor"] = "%{wks.location}/Volt/vendor/imgui-node-editor/"
IncludeDir["cr"] = "%{wks.location}/Volt/vendor/cr"
IncludeDir["msdf_atlas_gen"] = "%{wks.location}/Volt/vendor/msdf-atlas-gen/msdf-atlas-gen"
IncludeDir["msdfgen"] = "%{wks.location}/Volt/vendor/msdf-atlas-gen/msdfgen"
IncludeDir["PhysX"] = "%{wks.location}/Volt/vendor/PhysX/include"
IncludeDir["stb_image"] = "%{wks.location}/Volt/vendor/stb_image/"
IncludeDir["ffmpeg"] = "%{wks.location}/Volt/vendor/ffmpeg/include/"
IncludeDir["mono"] = "%{wks.location}/Volt/vendor/mono/include/"
IncludeDir["DirectXTex"] = "%{wks.location}/Volt/vendor/DirectXTex/src"
IncludeDir["fmod"] = "%{wks.location}/Amp/vendor/fmod/include"
IncludeDir["wwise"] = "%{wks.location}/Amp/vendor/wwise/include"
IncludeDir["efsw"] = "%{wks.location}/Volt/vendor/efsw/include"
IncludeDir["noise"] = "%{wks.location}/Volt/vendor/noise"
IncludeDir["asio"] = "%{wks.location}/Volt/vendor/asio/include"
IncludeDir["recast"] = "%{wks.location}/Navigation/vendor/recast/include"
IncludeDir["rcdtdebugutils"] = "%{wks.location}/Navigation/vendor/debugutils/include"
IncludeDir["detour"] = "%{wks.location}/Navigation/vendor/detour/include"
IncludeDir["detourcrowd"] = "%{wks.location}/Navigation/vendor/detourcrowd/include"
IncludeDir["detourtilecache"] = "%{wks.location}/Navigation/vendor/detourtilecache/include"
IncludeDir["fastlz"] = "%{wks.location}/Navigation/vendor/fastlz/include"
IncludeDir["TinyGLTF"] = "%{wks.location}/Volt/vendor/tiny_gltf/"
IncludeDir["half"] = "%{wks.location}/Volt/vendor/half/"
IncludeDir["steam"] = "%{wks.location}/Volt/vendor/steam/include"
IncludeDir["discord"] = "%{wks.location}/Volt/vendor/DiscordSDK/include"
IncludeDir["NFDExtended"] = "%{wks.location}/Volt/vendor/nfd-extended/src/include"
IncludeDir["TGAFbx"] = "%{wks.location}/Volt/vendor/TGAFbx/src"
IncludeDir["entt"] = "%{wks.location}/Volt/vendor/entt/include"
IncludeDir["cityhash"] = "%{wks.location}/Volt/vendor/cityhash/src"
IncludeDir["METIS"] = "%{wks.location}/Volt/vendor/METIS/include"
IncludeDir["GKLib"] = "%{wks.location}/Volt/vendor/GKLib"

IncludeDir["P4"] = "%{wks.location}/Sandbox/vendor/p4/include/"
IncludeDir["OpenSSL"] = "%{wks.location}/Sandbox/vendor/OpenSSL/include/"
IncludeDir["nlohmann"] = "%{wks.location}/Sandbox/vendor/nlohmann/include/"
IncludeDir["httplib"] = "%{wks.location}/Sandbox/vendor/cpp-httplib/include/"

IncludeDir["vma"] = "%{wks.location}/Volt/vendor/vma"
IncludeDir["VulkanSDK"] = "%{VULKAN_SDK}/Include"
IncludeDir["shaderc_utils"] = "%{wks.location}/Volt/vendor/shaderc/libshaderc_util/include"
IncludeDir["shaderc_glslc"] = "%{wks.location}/Volt/vendor/shaderc/glslc"
IncludeDir["Aftermath"] = "%{wks.location}/Volt/vendor/Aftermath/include"

IncludeDir["meshoptimizer"] = "%{wks.location}/Volt/vendor/meshoptimizer/src"

IncludeDir["CoreUtilities"] = "%{wks.location}/CoreUtilities/src"

LibraryDir = {}
LibraryDir["PhysX"] = "%{wks.location}/Volt/vendor/PhysX/lib/%{cfg.buildcfg}"
LibraryDir["fmod"] = "%{wks.location}/Volt/vendor/fmod/lib/%{cfg.buildcfg}"
LibraryDir["wwise"] = "%{wks.location}/Amp/vendor/wwise/lib/%{cfg.buildcfg}"
LibraryDir["ffmpeg"] = "%{wks.location}/Volt/vendor/ffmpeg/lib/"
LibraryDir["mono"] = "%{wks.location}/Volt/vendor/mono/lib/%{cfg.buildcfg}"
LibraryDir["steam"] = "%{wks.location}/Volt/vendor/steam/lib/win64"
LibraryDir["discord"] = "%{wks.location}/Volt/vendor/DiscordSDK/lib"

LibraryDir["P4"] = "%{wks.location}/Sandbox/vendor/p4/lib/%{cfg.buildcfg}"
LibraryDir["OpenSSL"] = "%{wks.location}/Sandbox/vendor/OpenSSL/lib/%{cfg.buildcfg}"

LibraryDir["Aftermath"] = "%{wks.location}/Volt/vendor/Aftermath/lib"

Library = {}
Library["fmod"] = "%{LibraryDir.fmod}/fmod_vc.lib"
Library["fmodstudio"] = "%{LibraryDir.fmod}/fmodstudio_vc.lib"
Library["fsbank"] = "%{LibraryDir.fmod}/fsbank_vc.lib"

Library["AkMemoryMgr"] = "%{LibraryDir.wwise}/AkMemoryMgr.lib"
Library["AkSoundEngine"] = "%{LibraryDir.wwise}/AkSoundEngine.lib"
Library["AkStreamMgr"] = "%{LibraryDir.wwise}/AkStreamMgr.lib"
Library["AkMusicEngine"] = "%{LibraryDir.wwise}/AkMusicEngine.lib"

Library["AkRoomVerbFX"] = "%{LibraryDir.wwise}/AkRoomVerbFX.lib"

Library["mono"] = "%{LibraryDir.mono}/libmono-static-sgen.lib"
Library["steam"] = "%{LibraryDir.steam}/steam_api64.lib"
Library["discord"] = "%{LibraryDir.discord}/discord_game_sdk.dll.lib"

LibraryDir["VulkanSDK"] = "%{VULKAN_SDK}/Lib"
LibraryDir["VulkanSDK_Debug"] = "%{VULKAN_SDK}/Lib"

Library["P4_client"] = "%{LibraryDir.P4}/libclient.lib"
Library["P4_api"] = "%{LibraryDir.P4}/libp4api.lib"
Library["P4_script"] = "%{LibraryDir.P4}/libp4script.lib"
Library["P4_script_c"] = "%{LibraryDir.P4}/libp4script_c.lib"
Library["P4_script_curl"] = "%{LibraryDir.P4}/libp4script_curl.lib"
Library["P4_script_sqlite"] = "%{LibraryDir.P4}/libp4script_sqlite.lib"
Library["P4_rpc"] = "%{LibraryDir.P4}/librpc.lib"
Library["P4_supp"] = "%{LibraryDir.P4}/libsupp.lib"

Library["OpenSSL_Crypto"] = "%{LibraryDir.OpenSSL}/libcrypto.lib"
Library["OpenSSL_SSL"] = "%{LibraryDir.OpenSSL}/libssl.lib"

Library["PhysX"] = "%{LibraryDir.PhysX}/PhysX.lib"

Library["avcodec"] = "%{LibraryDir.ffmpeg}/libavcodec.lib"  
Library["avdevice"] = "%{LibraryDir.ffmpeg}/libavdevice.lib"
Library["avfilter"] = "%{LibraryDir.ffmpeg}/libavfilter.lib"
Library["avformat"] = "%{LibraryDir.ffmpeg}/libavformat.lib"
Library["avutil"] = "%{LibraryDir.ffmpeg}/libavutil.lib"
Library["swresample"] = "%{LibraryDir.ffmpeg}/libswresample.lib"
Library["swscale"] = "%{LibraryDir.ffmpeg}/libswscale.lib"

Library["Vulkan"] = "%{LibraryDir.VulkanSDK}/vulkan-1.lib"
Library["dxc"] = "%{wks.location}/Volt/vendor/dxc/dxcompiler.lib"

Library["ShaderC_Debug"] = "%{LibraryDir.VulkanSDK_Debug}/shaderc_sharedd.lib"
Library["ShaderC_Utils_Debug"] = "%{LibraryDir.VulkanSDK_Debug}/shaderc_utild.lib"
Library["SPIRV_Cross_Debug"] = "%{LibraryDir.VulkanSDK_Debug}/spirv-cross-cored.lib"
Library["SPIRV_Cross_GLSL_Debug"] = "%{LibraryDir.VulkanSDK_Debug}/spirv-cross-glsld.lib"
Library["SPIRV_Tools_Debug"] = "%{LibraryDir.VulkanSDK_Debug}/SPIRV-Toolsd.lib"

Library["ShaderC_Release"] = "%{LibraryDir.VulkanSDK}/shaderc_shared.lib"
Library["ShaderC_Utils_Release"] = "%{LibraryDir.VulkanSDK}/shaderc_util.lib"
Library["SPIRV_Cross_Release"] = "%{LibraryDir.VulkanSDK}/spirv-cross-core.lib"
Library["SPIRV_Cross_GLSL_Release"] = "%{LibraryDir.VulkanSDK}/spirv-cross-glsl.lib"

Library["Aftermath"] = "%{LibraryDir.Aftermath}/x64/GFSDK_Aftermath_Lib.x64.lib"