#pragma once

#include <optick.h>

#define VT_ENABLE_PROFILING 1

#if VT_ENABLE_PROFILING
#define VT_PROFILE_FRAME(...) OPTICK_FRAME(__VA_ARGS__)
#define VT_PROFILE_FUNCTION(...)  OPTICK_EVENT(__VA_ARGS__)
#define VT_PROFILE_TAG(NAME, ...) OPTICK_TAG(NAME, __VA_ARGS__)
#define VT_PROFILE_SCOPE(NAME) OPTICK_EVENT_DYNAMIC(NAME)
#define VT_PROFILE_THREAD(...) OPTICK_THREAD(__VA_ARGS__)
#define VT_PROFILE_CATEGORY(...) OPTICK_CATEGORY(__VA_ARGS__)
#else
#define VT_PROFILE_FRAME(...)
#define VT_PROFILE_FUNCTION(...)
#define VT_PROFILE_TAG(NAME, ...)
#define VT_PROFILE_SCOPE(NAME)
#define VT_PROFILE_THREAD(...)
#endif