#pragma once

#ifdef RENDERCOREMODULE_DLL_EXPORT
#define VTRC_API __declspec(dllexport)
#else
#define VTRC_API __declspec(dllimport)
#endif

#ifdef VT_DEBUG

#define VT_ENABLE_SHADER_RUNTIME_VALIDATION
#define VT_ENABLE_RENDERGRAPH_DEBUG_LOG
#define VT_ENABLE_RENDERGRAPH_VALIDATION

#elif VT_DEVELOPMENT

#define VT_ENABLE_SHADER_RUNTIME_VALIDATION
#define VT_ENABLE_RENDERGRAPH_VALIDATION

#elif VT_DIST

#endif
