#ifndef DEFINES_H
#define DEFINES_H

#define SPACE_TEXTURES 0
#define SPACE_MAINBUFFERS 1
#define SPACE_SAMPLERS 2
#define SPACE_RENDERER_BUFFERS 3

#define SPACE_OTHER 4
#define SPACE_PBR_RESOURCES 5
#define SPACE_MATERIAL 6
#define SPACE_DRAW_BUFFERS 7

///// Binding Defines /////

// Space 0
#define BINDING_TEXTURE2DTABLE 0
#define BINDING_TEXTURECUBETABLE 1
#define BINDING_TEXTURE3DTABLE 2

// Space 1
#define BINDING_MATERIALTABLE 0

// Space 2
#define SAMPLER_LINEAR 0
#define SAMPLER_LINEAR_POINT 1
#define SAMPLER_POINT 2
#define SAMPLER_POINT_LINEAR 3

#define SAMPLER_LINEAR_CLAMP 4
#define SAMPLER_LINEAR_POINT_CLAMP 5
#define SAMPLER_POINT_CLAMP 6
#define SAMPLER_POINT_LINEAR_CLAMP 7

#define SAMPLER_ANISO 8
#define SAMPLER_SHADOW 9

// Space 3
#define BINDING_CAMERABUFFER 1
#define BINDING_INDIRECT_ARGS 2
#define BINDING_OBJECT_DATA 4
#define BINDING_DIRECTIONAL_LIGHT 6
#define BINDING_POINT_LIGHTS 7
#define BINDING_SCENE_DATA 8
#define BINDING_SPOT_LIGHTS 9
#define BINDING_ANIMATION_DATA 10
#define BINDING_SPHERE_LIGHTS 11
#define BINDING_RECTANGLE_LIGHTS 12
#define BINDING_PARTICLE_INFO 13
#define BINDING_VISIBLE_POINT_LIGHTS 14
#define BINDING_RENDERER_DATA 15
#define BINDING_PAINTED_VERTEX_COLORS 16
#define BINDING_VISIBLE_SPOT_LIGHTS 17

// Space 5
#define BINDING_BRDF 0
#define BINDING_IRRADIANCE 1
#define BINDING_RADIANCE 2
#define BINDING_DIR_SHADOWMAP 3

// Space 7
#define BINDING_INDIRECT_COUNT 0
#define BINDING_DRAW_TO_OBJECT_ID 1

#endif